#!/usr/bin/env python
"""This module brings together and exports target/disease evidence generated by AzGeneBurden.py and RegeneronGeneBurdeb.py."""

import argparse
from functools import partial, reduce
import logging
import sys

from pyspark import SparkFiles
from pyspark.sql import SparkSession
from pyspark.sql.dataframe import DataFrame
from pyspark.sql.functions import array, col, concat, lit, when
from pyspark.sql.types import StringType

from common.evidence import initialize_sparksession, write_evidence_strings
from RegeneronGeneBurden import main as process_regeneron_gene_burden
from AzGeneBurden import main as process_az_gene_burden


def main(
    az_binary_data: str,
    az_quant_data: str,
    az_trait_mappings: str,
    regeneron_data: str,
    gwas_studies: str,
    curated_data: str,
    spark_instance: SparkSession,
) -> DataFrame:
    """This module brings together and exports target/disease evidence generated by AzGeneBurden.py and RegeneronGeneBurdeb.py."""

    burden_evidence_sets = [
    # Generate evidence from regeneron data:
    process_regeneron_gene_burden(regeneron_data, gwas_studies, spark_instance=spark_instance).persist(),
    
    # Generate evidence from AZ data:
    process_az_gene_burden(az_binary_data, az_quant_data, az_trait_mappings, spark_instance=spark_instance).persist(),
    
    # Generate evidence from manual data:
    process_gene_burden_curation(curated_data, spark_instance=spark_instance).persist()
    ]

    unionByDiffSchema = partial(DataFrame.unionByName, allowMissingColumns=True)
    evd_df = reduce(unionByDiffSchema, burden_evidence_sets)
    logging.info(f'Total number of gene_burden evidence: {evd_df.count()}')

    return evd_df

def process_gene_burden_curation(curated_data: str, spark_instance: SparkSession) -> DataFrame:
    """Process manual gene burden evidence."""
    
    logging.info(f'File with the curated burden associations: {curated_data}')
    manual_df = read_gene_burden_curation(curated_data, spark_instance)
    logging.info(f'Total number of imported manual gene_burden evidence: {manual_df.count()}')

    return (
        manual_df
        # The columns practically follow the schema, only small things need to be parsed
        # 1. Confidence intervals are detached
        .withColumn('oddsRatioConfidenceIntervalLower', when(col('oddsRatio').isNotNull(), col('ConfidenceIntervalLower')))
        .withColumn('oddsRatioConfidenceIntervalUpper', when(col('oddsRatio').isNotNull(), col('ConfidenceIntervalUpper')))
        .withColumn('betaConfidenceIntervalLower', when(col('beta').isNotNull(), col('ConfidenceIntervalLower')))
        .withColumn('betaConfidenceIntervalUpper', when(col('beta').isNotNull(), col('ConfidenceIntervalUpper')))

        # 2. Gene specific URLs are available for the SCHEMA, epilepsy and ASC consortia data
        .withColumn(
            'url',
            when(col('projectId').isin(['SCHEMA consortium', 'Epi25 collaborative', 'Autism Sequencing Consortium']), concat(col('url'), lit('/gene/'), col('targetFromSourceId')))
        )

        # 3. Collect PMID in an array
        .withColumn('literature', array(col('literature').cast(StringType())))
    )

def read_gene_burden_curation(curated_data: str, spark_instance: SparkSession) -> DataFrame:
    """Read manual gene burden curation from remote to a Spark DataFrame."""
    
    spark.sparkContext.addFile(curated_data)

    return spark_instance.read.csv(SparkFiles.get(curated_data.split('/')[-1]), sep='\t', header=True, inferSchema=True)

def get_parser():
    """Get parser object for script GeneBurden.py."""
    parser = argparse.ArgumentParser(description=__doc__)

    parser.add_argument(
        '--az_binary_data',
        help='Input parquet files with AZ\'s PheWAS associations of binary traits.',
        type=str,
        required=True,
    )
    parser.add_argument(
        '--az_quant_data',
        help='Input parquet files with AZ\'s PheWAS associations of quantitative traits.',
        type=str,
        required=True,
    )
    parser.add_argument(
        '--regeneron_data',
        help='Input Excel file with the data published in PMID:34662886.',
        type=str,
        required=True,
    )
    parser.add_argument(
        '--gwas_studies',
        help='Input TSV containing all GWAS Catalog studies.',
        type=str,
        required=True,
    )
    parser.add_argument(
        '--az_trait_mappings',
        help='Input Excel containing the AZ traits with their EFO mappings.',
        type=str,
        required=True,
    )
    parser.add_argument(
        '--curated_data',
        help='Input remote CSV file containing the gene burden manual curation.',
        type=str,
        required=True,
    )
    parser.add_argument(
        '--output',
        help='Output gzipped json file following the gene_burden evidence data model.',
        type=str,
        required=True,
    )
    parser.add_argument(
        '--log_file',
        help='Destination of the logs generated by this script. Defaults to None',
        type=str,
        nargs='?',
        default=None,
    )

    return parser


if __name__ == "__main__":
    args = get_parser().parse_args()

    # Logger initializer. If no log_file is specified, logs are written to stderr
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s %(levelname)s %(module)s - %(funcName)s: %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S',
    )
    if args.log_file:
        logging.config.fileConfig(filename=args.log_file)
    else:
        logging.StreamHandler(sys.stderr)

    spark = initialize_sparksession()

    evd_df = main(
        az_binary_data=args.az_binary_data,
        az_quant_data=args.az_quant_data,
        az_trait_mappings=args.az_trait_mappings,
        regeneron_data=args.regeneron_data,
        gwas_studies=args.gwas_studies,
        curated_data=args.curated_data,
        spark_instance=spark,
    )

    write_evidence_strings(evd_df, args.output)
    logging.info(f'Evidence strings have been saved to {args.output}. Exiting.')
